# Generated by Django 6.0 on 2026-01-10 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ravelry_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('yarn_weight', models.CharField(max_length=50)),
                ('photo_url', models.URLField(blank=True)),
                ('source', models.CharField(default='ravelry', max_length=20)),
                ('pattern_url', models.URLField(blank=True, verbose_name='Ссылка на схему')),
                ('difficulty', models.CharField(blank=True, choices=[('beginner', 'Начинающий'), ('easy', 'Легкий'), ('intermediate', 'Средний'), ('experienced', 'Опытный')], max_length=20)),
                ('craft', models.CharField(choices=[('knitting', 'Вязание'), ('crochet', 'Вязание крючком')], default='knitting', max_length=20)),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатная')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('rating_count', models.IntegerField(default=0, verbose_name='Количество оценок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('in_progress', 'В процессе'), ('completed', 'Завершен'), ('frogged', 'Распущен')], default='planned', max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('progress', models.IntegerField(default=0, verbose_name='Прогресс (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yarn_app.pattern')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserYarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название пряжи')),
                ('yarn_type', models.CharField(choices=[('fingering', 'Тонкая (Fingering)'), ('sport', 'Спортивная (Sport)'), ('dk', 'Средняя (DK)'), ('worsted', 'Камвольная (Worsted)'), ('bulky', 'Толстая (Bulky)'), ('other', 'Другая')], max_length=20, verbose_name='Тип пряжи')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
                ('amount', models.IntegerField(verbose_name='Количество (мотки)')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Вес (г)')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Производитель')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yarn_app.pattern')),
            ],
            options={
                'unique_together': {('user', 'pattern')},
            },
        ),
        migrations.CreateModel(
            name='ProjectYarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_used', models.IntegerField(verbose_name='Использовано мотков')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания по использованию')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_yarns', to='yarn_app.project')),
                ('user_yarn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yarn_app.useryarn')),
            ],
            options={
                'unique_together': {('project', 'user_yarn')},
            },
        ),
    ]
