# Generated by Django 6.0 on 2026-01-03 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ravelry_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('yarn_weight', models.CharField(max_length=50)),
                ('photo_url', models.URLField(blank=True)),
                ('source', models.CharField(default='ravelry', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserYarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yarn_type', models.CharField(choices=[('fingering', 'Тонкая (Fingering)'), ('sport', 'Спортивная (Sport)'), ('dk', 'Средняя (DK)'), ('worsted', 'Камвольная (Worsted)'), ('bulky', 'Толстая (Bulky)')], max_length=20)),
                ('color', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yarn_app.pattern')),
            ],
            options={
                'unique_together': {('user', 'pattern')},
            },
        ),
    ]
