# Generated by Django 6.0 on 2026-01-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarn_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useryarn',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название пряжи'),
        ),
        migrations.AddField(
            model_name='useryarn',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес (грамм)'),
        ),
        migrations.AlterField(
            model_name='useryarn',
            name='amount',
            field=models.IntegerField(verbose_name='Количество мотков'),
        ),
        migrations.AlterField(
            model_name='useryarn',
            name='color',
            field=models.CharField(max_length=30, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='useryarn',
            name='yarn_type',
            field=models.CharField(choices=[('fingering', 'Тонкая (Fingering)'), ('sport', 'Спортивная (Sport)'), ('dk', 'Средняя (DK)'), ('worsted', 'Камвольная (Worsted)'), ('bulky', 'Толстая (Bulky)')], max_length=20, verbose_name='Тип пряжи'),
        ),
    ]
