# Generated by Django 6.0 on 2026-01-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarn_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
