# Generated by Django 6.0 on 2026-01-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarn_app', '0002_useryarn_name_useryarn_weight_alter_useryarn_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useryarn',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='useryarn',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='useryarn',
            name='amount',
            field=models.IntegerField(verbose_name='Количество (мотки)'),
        ),
        migrations.AlterField(
            model_name='useryarn',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название пряжи'),
        ),
        migrations.AlterField(
            model_name='useryarn',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес (г)'),
        ),
        migrations.AlterField(
            model_name='useryarn',
            name='yarn_type',
            field=models.CharField(choices=[('fingering', 'Тонкая (Fingering)'), ('sport', 'Спортивная (Sport)'), ('dk', 'Средняя (DK)'), ('worsted', 'Камвольная (Worsted)'), ('bulky', 'Толстая (Bulky)'), ('other', 'Другая')], max_length=20, verbose_name='Тип пряжи'),
        ),
    ]
