# Generated by Django 6.0 on 2026-01-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarn_app', '0002_pattern_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория'),
        ),
    ]
