# Generated by Django 6.0.1 on 2026-01-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarn_app', '0003_pattern_author_pattern_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='published',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='yardage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Метраж (ярды)'),
        ),
    ]
